import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type OrderDocument = Order & Document;

@Schema({ timestamps: true })
export class Order {
  // -- Order Identity ------------------------------------
  /** e.g. SB-20241225-0001 � generated by service before save */
  @Prop({ required: true, unique: true, uppercase: true, trim: true })
  orderNumber: string;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  customer: Types.ObjectId;

  // -- Line Items ----------------------------------------
  @Prop({
    type: [
      {
        product: { type: Types.ObjectId, ref: 'Product', required: true },
        seller: { type: Types.ObjectId, ref: 'Seller', required: true },
        /** Snapshot: title at time of order */
        title: { type: String, required: true },
        /** Snapshot: primary image at time of order */
        image: { type: String, default: '' },
        /** Selected variant details, e.g. {Color:'Red', Size:'XL'} */
        variant: { type: Object, default: {} },
        sku: { type: String, default: '' },
        quantity: { type: Number, required: true, min: 1 },
        /** Unit price at time of order */
        price: { type: Number, required: true, min: 0 },
        subtotal: { type: Number, required: true, min: 0 },
        /** Per-item fulfilment status */
        status: {
          type: String,
          enum: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned'],
          default: 'pending',
        },
        trackingNumber: { type: String, default: '' },
        courier: { type: String, default: '' },
        cancelReason: { type: String, default: '' },
        returnReason: { type: String, default: '' },
        shippedAt: { type: Date },
        deliveredAt: { type: Date },
        /** Commission platform takes from this item */
        platformCommission: { type: Number, default: 0 },
      },
    ],
    required: true,
  })
  items: {
    product: Types.ObjectId;
    seller: Types.ObjectId;
    title: string;
    image: string;
    variant: any;
    sku: string;
    quantity: number;
    price: number;
    subtotal: number;
    status: string;
    trackingNumber: string;
    courier: string;
    cancelReason: string;
    returnReason: string;
    shippedAt?: Date;
    deliveredAt?: Date;
    platformCommission: number;
  }[];

  // -- Shipping Address (snapshot at order time) ---------
  @Prop({
    type: {
      label: { type: String, default: 'Home' },
      name: { type: String, required: true },
      phone: { type: String, required: true },
      street: { type: String, required: true },
      city: { type: String, required: true },
      state: { type: String, required: true },
      zip: { type: String, default: '' },
      country: { type: String, default: 'Bangladesh' },
    },
    required: true,
  })
  shippingAddress: {
    label: string;
    name: string;
    phone: string;
    street: string;
    city: string;
    state: string;
    zip: string;
    country: string;
  };

  // -- Financials ----------------------------------------
  @Prop({ required: true, min: 0 })
  subtotal: number;

  @Prop({ default: 0, min: 0 })
  shippingFee: number;

  @Prop({ default: 0, min: 0 })
  discount: number;

  /** subtotal + shippingFee - discount */
  @Prop({ required: true, min: 0 })
  total: number;

  // -- Payment -------------------------------------------
  @Prop({
    type: String,
    enum: ['cod', 'bkash', 'nagad', 'rocket', 'bank_transfer'],
    required: true,
  })
  paymentMethod: string;

  @Prop({
    type: String,
    enum: ['pending', 'paid', 'failed', 'refunded', 'cod_pending', 'cod_collected'],
    default: 'pending',
  })
  paymentStatus: string;

  @Prop({ default: '' })
  paymentTransactionId: string;

  @Prop({ type: Types.ObjectId, ref: 'Payment' })
  payment: Types.ObjectId;

  // -- Coupon --------------------------------------------
  @Prop({ type: Types.ObjectId, ref: 'Coupon' })
  coupon: Types.ObjectId;

  @Prop({ default: '' })
  couponCode: string;

  // -- Order-level Status --------------------------------
  @Prop({
    type: String,
    enum: ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', 'refunded'],
    default: 'pending',
  })
  status: string;

  @Prop({ default: '' })
  cancellationReason: string;

  @Prop({ default: '' })
  returnReason: string;

  // -- Timeline ------------------------------------------
  @Prop({ type: Date })
  confirmedAt: Date;

  @Prop({ type: Date })
  processedAt: Date;

  @Prop({ type: Date })
  shippedAt: Date;

  @Prop({ type: Date })
  deliveredAt: Date;

  @Prop({ type: Date })
  cancelledAt: Date;

  @Prop({ type: Date })
  returnedAt: Date;

  @Prop({ type: Date })
  estimatedDelivery: Date;

  // -- Misc ----------------------------------------------
  @Prop({ default: '' })
  notes: string;

  @Prop({ default: '' })
  invoiceUrl: string;

  @Prop({ default: false })
  isReviewed: boolean;
}

export const OrderSchema = SchemaFactory.createForClass(Order);

// --- Indexes ------------------------------------------------------------------
OrderSchema.index({ orderNumber: 1 }, { unique: true });
OrderSchema.index({ customer: 1, createdAt: -1 });
OrderSchema.index({ status: 1 });
OrderSchema.index({ paymentStatus: 1 });
OrderSchema.index({ createdAt: -1 });
OrderSchema.index({ 'items.seller': 1, createdAt: -1 });
OrderSchema.index({ 'items.status': 1 });
// Admin revenue queries
OrderSchema.index({ status: 1, paymentStatus: 1, createdAt: -1 });
